/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAlert: typeof import('./src/components/UI/AppAlert.vue')['default']
    AppButton: typeof import('./src/components/UI/AppButton.vue')['default']
    AppConfirmModal: typeof import('./src/components/UI/AppConfirmModal.vue')['default']
    AppError: typeof import('./src/components/UI/AppError.vue')['default']
    AppFooter: typeof import('./src/components/core/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/core/AppHeader.vue')['default']
    AppInput: typeof import('./src/components/UI/AppInput.vue')['default']
    AppModal: typeof import('./src/components/UI/AppModal.vue')['default']
    AppSkeleton: typeof import('./src/components/UI/AppSkeleton.vue')['default']
    AppSpinner: typeof import('./src/components/UI/AppSpinner.vue')['default']
    DeleteConfirmModal: typeof import('./src/components/employees/DeleteConfirmModal.vue')['default']
    EmployeeForm: typeof import('./src/components/employees/EmployeeForm.vue')['default']
    EmployeeFormModal: typeof import('./src/components/employees/EmployeeFormModal.vue')['default']
    EmployeesTable: typeof import('./src/components/employees/EmployeesTable.vue')['default']
    'IFluent:dismiss24Regular': typeof import('~icons/fluent/dismiss24-regular')['default']
    'IGravityUi:arrowPath': typeof import('~icons/gravity-ui/arrow-path')['default']
    'IGravityUi:plus': typeof import('~icons/gravity-ui/plus')['default']
    'IIc:round-': typeof import('~icons/ic/round-')['default']
    'IIc:roundAdd': typeof import('~icons/ic/round-add')['default']
    'IIc:roundClose': typeof import('~icons/ic/round-close')['default']
    'IIc:roundDelete': typeof import('~icons/ic/round-delete')['default']
    'IIc:roundEdit': typeof import('~icons/ic/round-edit')['default']
    'IIc:roundPersonPin': typeof import('~icons/ic/round-person-pin')['default']
    'IIc:roundPl': typeof import('~icons/ic/round-pl')['default']
    'IIc:roundPlace': typeof import('~icons/ic/round-place')['default']
    'IIc:roundPlu': typeof import('~icons/ic/round-plu')['default']
    'IIc:roundPlus': typeof import('~icons/ic/round-plus')['default']
    'IIc:roundPlus?': typeof import('~icons/ic/round-plus?')['default']
    'ISvgSpinners:180Ring': typeof import('~icons/svg-spinners/180-ring')['default']
    'ISvgSpinners:barsRotateFade': typeof import('~icons/svg-spinners/bars-rotate-fade')['default']
    'ITabler:faceIdError': typeof import('~icons/tabler/face-id-error')['default']
    'ITabler:plus': typeof import('~icons/tabler/plus')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
